export type Diretoria = 'Dim' | 'Dinter 1' | 'Dinter 2' | 'Diresp';

export const BATALHAO_POR_DIRETORIA = {
  'ESCOLHA A UNIDADE...': 'Dim',

  '1º BATALHAO DE POLICIA MILITAR': 'Dim',
  '6º BATALHAO DE POLICIA MILITAR': 'Dim',
  '11º BATALHAO DE POLICIA MILITAR': 'Dim',
  '12º BATALHAO DE POLICIA MILITAR': 'Dim',
  '13º BATALHAO DE POLICIA MILITAR': 'Dim',
  '16º BATALHAO DE POLICIA MILITAR': 'Dim',
  '19º BATALHAO DE POLICIA MILITAR': 'Dim',
  '20º BATALHAO DE POLICIA MILITAR': 'Dim',
  '25º BATALHAO DE POLICIA MILITAR': 'Dim',
  '26º BATALHAO DE POLICIA MILITAR': 'Dim',

  '2º BATALHAO DE POLICIA MILITAR': 'Dinter 1',
  '4º BATALHAO DE POLICIA MILITAR': 'Dinter 1',
  '9º BATALHAO DE POLICIA MILITAR': 'Dinter 1',
  '10º BATALHAO DE POLICIA MILITAR': 'Dinter 1',
  '15º BATALHAO DE POLICIA MILITAR': 'Dinter 1',
  '21º BATALHAO DE POLICIA MILITAR': 'Dinter 1',
  '22º BATALHAO DE POLICIA MILITAR': 'Dinter 1',
  '24º BATALHÃO DE POLÍCIA MILITAR': 'Dinter 1',

  '3º BATALHAO DE POLICIA MILITAR': 'Dinter 2',
  '5º BATALHAO DE POLICIA MILITAR': 'Dinter 2',
  '7º BATALHAO DE POLICIA MILITAR': 'Dinter 2',
  '8º BATALHAO DE POLICIA MILITAR': 'Dinter 2',
  '14º BATALHAO DE POLICIA MILITAR': 'Dinter 2',
  '23º BATALHAO DE POLICIA MILITAR': 'Dinter 2',

  '1ª COMPANHIA INDEPENDENTE DE POLICIA MILITAR': 'Dinter 2',
  '2ª COMPANHIA INDEPENDENTE DA POLICIA MILITAR': 'Dinter 2',
  '4ª COMPANHIA INDEPENDENTE DE POLICIA MILITAR': 'Dinter 2',

  '17º BATALHAO DE POLICIA MILITAR': 'Diresp',
  '18º BATALHAO DE POLICIA MILITAR ': 'Diresp',

  '1º BPTRAN - BATALHÃO DE POLICIAMENTO DE TRÂNSITO': 'Diresp',
  '1º BIESP - BATALHÃO INTEGRADO ESPECIALIZADO DE POLICIAMENTO': 'Diresp',
  '2º BIESP - BATALHÃO INTEGRADO ESPECIALIZADO DE POLICIAMENTO': 'Diresp',
  'BATALHÃO DE POLICIAMENTO AMBIENTAL': 'Diresp',
  'BATALHAO DE POLICIA DE CHOQUE': 'Diresp',
  'BATALHAO DE POLICIA DE GUARDA': 'Diresp',
  'BATALHAO DE POLICIA RODOVIARIA': 'Diresp',
  'BATALHAO DE RADIO PATRULHA': 'Diresp',
  'BATALHÃO DE OPERAÇÕES ESPECIAIS': 'Diresp',
  'BPTUR - BATALHAO DE POLICIAMENTO AO TURISTA': 'Diresp',
  'CIPCAES - COMPANHIA INDEPENDENTE DE POLICIAMENTO COM CÃES': 'Diresp',
  'CIPMOTO - COMPANHIA INDEPENDENTE DE POLICIAMENTO COM MOTOS': 'Diresp',
  'BEPI - BATALHÃO ESPECIALIZADO DE POLICIAMENTO DO INTERIOR': 'Diresp',
  'REGIMENTO DE POLICIA MONTADA - DIAS CARDOSO': 'Diresp',
  'CORREGEDORIA GERAL DE POLICIA': 'Diresp',
  'GRUPAMENTO TÁTICO AEREO': 'Diresp',
  'SDS / OPERAÇÃO LEI SECA': 'Diresp',
  'DIRETORIA DE ARTICULAÇÃO SOCIAL E DIREITOS HUMANOS': 'Diresp'
} as const;

export type Batalhao = keyof typeof BATALHAO_POR_DIRETORIA;

function isBatalhao(value: string): value is Batalhao {
  return value in BATALHAO_POR_DIRETORIA;
}

export class BuscaDiretoriaPorBatalhao {
  static execute(codigoBatalhao?: string): Diretoria | null {
    if (!codigoBatalhao) return null;
    if (!isBatalhao(codigoBatalhao)) return null;
    return BATALHAO_POR_DIRETORIA[codigoBatalhao];
  }
}
